### ISSUE TITLE
symbolic links not expanded for nested directories.

### ISSUE THREAD

**Issue by rubenhak** [timkendrick/recursive-copy#11]
Looks like there is missing second argument on line 194.
Instead of:
`return getFileListing(filePath)`
this is needed:
`return getFileListing(filePath, shouldExpandSymlinks)`

Thanks.

**Comment by timkendrick** [comment]
Thanks for the excellent bug report! I've just published [v2.0.9](https://www.npmjs.com/package/recursive-copy) that fixes this.

Let me know if you have any more problems.
