### ISSUE TITLE
Modified Time on File

### ISSUE THREAD

**Issue by psalmody** [timkendrick/recursive-copy#14]
Would be awesome to have an option to preserve mtime on files as they are copied (Windows does this when you copy files). Right now I'm doing:

```js
copy(file, dest)
  .on(copy.events.COPY_FILE_COMPLETE, function(copyOperation) {
      //update atime and mtime
     let s = fs.statSync(copyOperation.src)
     fs.utimesSync(copyOperation.dest, s.atime, s.mtime)
  })
```

which works but I think this could be a nice feature to add.

**Comment by timkendrick** [comment]
Good catch! Fixed in [v2.0.10](https://www.npmjs.com/package/recursive-copy).

Feel free to reopen this issue if you're still having problems.
