### ISSUE TITLE
@types/recursive-copy is missing

### ISSUE THREAD

**Issue by AlenPelin** [timkendrick/recursive-copy#16]
It will be great if the module has definitely typed annotations to be used in typescript.

**Comment by amyboyd** [comment]
Done in https://github.com/timkendrick/recursive-copy/pull/19/files

**Comment by timkendrick** [comment]
Released as [v2.0.11](https://www.npmjs.com/package/recursive-copy/v/2.0.11) - big shout out to @amyboyd for making this happen! 🎉
