### ISSUE TITLE
emitter-mixin issues warnings

### ISSUE THREAD

**Issue by gbirke** [timkendrick/recursive-copy#24]
When using the library (a dependency of eleventy.js), I get the following warning:

```
DeprecationWarning: Invalid 'main' field in '/app/node_modules/emitter-mixin/package.json' of 'y'. 
Please either fix that or report it to the module author
```

I had a look at the [emitter-mixin](https://github.com/yields/emitter-mixin) repository and saw that it's archived, so it's unlikely that the author will fix the `package.json` entry. 

Please replace the library with a different implementation.

**Comment by timkendrick** [comment]
Thanks for reporting!

This should be fixed in [v2.0.12](https://www.npmjs.com/package/recursive-copy/v/2.0.12) - feel free to reopen this issue if you're still having problems.
