### ISSUE TITLE
How copy `src` folder?

### ISSUE THREAD

**Issue by bySabi** [timkendrick/recursive-copy#6]
Maybe is too obvious but I can´t see it

I can copy `src` content but not folder.

**Comment by timkendrick** [comment]
If I understand correctly, you're trying to copy the whole `src` folder *inside* the `dest` folder, rather than transferring its contents?

If so, try using `dest/src` as the destination path:

```js
var copy = require('recursive-copy');
 
copy('src', 'dest/src')
    .then(function(results) {
        console.info('Copied ' + results.length + ' files');
    })
    .catch(function(error) {
        console.error('Copy failed: ' + error);
    });
```

Let me know if you're still having problems, otherwise feel free to close the issue.

**Comment by bySabi** [comment]
it works!

Well done!
Thanks
